BOOK_ALIASES = {
    "gen": "genesis", "ge": "genesis", "gn": "genesis",
    "ex": "exodus", "exo": "exodus",
    "lev": "leviticus", "lv": "leviticus",
    "num": "numbers", "nu": "numbers", "nm": "numbers",
    "deut": "deuteronomy", "dt": "deuteronomy",
    "josh": "joshua", "jos": "joshua",
    "judg": "judges", "jdg": "judges", "jg": "judges",
    "ruth": "ruth", "ru": "ruth",
    "1sam": "1_samuel", "1 sam": "1_samuel", "i sam": "1_samuel",
    "2sam": "2_samuel", "2 sam": "2_samuel", "ii sam": "2_samuel",
    "1kgs": "1_kings", "1 kgs": "1_kings", "i kings": "1_kings",
    "2kgs": "2_kings", "2 kgs": "2_kings", "ii kings": "2_kings",
    "1chr": "1_chronicles", "1 chr": "1_chronicles", "i chronicles": "1_chronicles",
    "2chr": "2_chronicles", "2 chr": "2_chronicles", "ii chronicles": "2_chronicles",
    "ezra": "ezra", "neh": "nehemiah", "esth": "esther", "est": "esther",
    "job": "job", "ps": "psalms", "psa": "psalms", "psalm": "psalms",
    "prov": "proverbs", "pr": "proverbs",
    "eccl": "ecclesiastes", "ecc": "ecclesiastes",
    "song": "song_of_songs", "sos": "song_of_songs",
    "isa": "isaiah", "jer": "jeremiah", "lam": "lamentations",
    "ezek": "ezekiel", "ezk": "ezekiel", "dan": "daniel",
    "hos": "hosea", "joel": "joel", "amos": "amos", "obad": "obadiah",
    "jon": "jonah", "mic": "micah", "nah": "nahum", "hab": "habakkuk",
    "zeph": "zephaniah", "hag": "haggai", "zech": "zechariah", "mal": "malachi",
    "mt": "matthew", "matt": "matthew",
    "mk": "mark", "mrk": "mark",
    "lk": "luke", "luk": "luke",
    "jn": "john", "jhn": "john",
    "acts": "acts",
    "rom": "romans",
    "1cor": "1_corinthians", "1 cor": "1_corinthians", "i cor": "1_corinthians",
    "2cor": "2_corinthians", "2 cor": "2_corinthians", "ii cor": "2_corinthians",
    "gal": "galatians", "eph": "ephesians",
    "phil": "philippians", "php": "philippians",
    "col": "colossians",
    "1th": "1_thessalonians", "1 thess": "1_thessalonians",
    "2th": "2_thessalonians", "2 thess": "2_thessalonians",
    "1tim": "1_timothy", "2tim": "2_timothy",
    "tit": "titus", "phm": "philemon",
    "heb": "hebrews",
    "jam": "james", "jas": "james",
    "1pet": "1_peter", "2pet": "2_peter",
    "1jn": "1_john", "2jn": "2_john", "3jn": "3_john",
    "jude": "jude",
    "rev": "revelation", "re": "revelation",
}
