BOOK_ALIASES = {
    "gen": "genesis", "ge": "genesis", "gn": "genesis",
    "ex": "exodus", "exo": "exodus",
    "lev": "leviticus", "lv": "leviticus",
    "num": "numbers", "nu": "numbers", "nm": "numbers",
    "deut": "deuteronomy", "dt": "deuteronomy",
    "josh": "joshua", "jos": "joshua",
    "judg": "judges", "jdg": "judges", "jg": "judges",
    "ruth": "ruth", "ru": "ruth",
    "1sam": "1 samuel", "1 sam": "1 samuel", "i sam": "1 samuel",
    "2sam": "2 samuel", "2 sam": "2 samuel", "ii sam": "2 samuel",
    "1kgs": "1 kings", "1 kgs": "1 kings", "i kings": "1 kings",
    "2kgs": "2 kings", "2 kgs": "2 kings", "ii kings": "2 kings",
    "1chr": "1 chronicles", "1 chr": "1 chronicles", "i chronicles": "1 chronicles",
    "2chr": "2 chronicles", "2 chr": "2 chronicles", "ii chronicles": "2 chronicles",
    "ezra": "ezra", "neh": "nehemiah", "esth": "esther", "est": "esther",
    "job": "job", "ps": "psalms", "psa": "psalms", "psalm": "psalms",
    "prov": "proverbs", "pr": "proverbs",
    "eccl": "ecclesiastes", "ecc": "ecclesiastes",
    "song": "song of songs", "sos": "song of songs",
    "isa": "isaiah", "jer": "jeremiah", "lam": "lamentations",
    "ezek": "ezekiel", "ezk": "ezekiel", "dan": "daniel",
    "hos": "hosea", "joel": "joel", "amos": "amos", "obad": "obadiah",
    "jon": "jonah", "mic": "micah", "nah": "nahum", "hab": "habakkuk",
    "zeph": "zephaniah", "hag": "haggai", "zech": "zechariah", "mal": "malachi",
    "mt": "matthew", "matt": "matthew",
    "mk": "mark", "mrk": "mark",
    "lk": "luke", "luk": "luke",
    "jn": "john", "jhn": "john",
    "acts": "acts",
    "rom": "romans",
    "1cor": "1 corinthians", "1 cor": "1 corinthians", "i cor": "1 corinthians",
    "2cor": "2 corinthians", "2 cor": "2 corinthians", "ii cor": "2 corinthians",
    "gal": "galatians", "eph": "ephesians",
    "phil": "philippians", "php": "philippians",
    "col": "colossians",
    "1th": "1 thessalonians", "1 thess": "1 thessalonians",
    "2th": "2 thessalonians", "2 thess": "2 thessalonians",
    "1tim": "1 timothy", "2tim": "2 timothy",
    "tit": "titus", "phm": "philemon",
    "heb": "hebrews",
    "jam": "james", "jas": "james",
    "1pet": "1 peter", "2pet": "2 peter",
    "1jn": "1 john", "2jn": "2 john", "3jn": "3 john",
    "jude": "jude",
    "rev": "revelation", "re": "revelation",
}